name: futureacademy
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: null
  cupertino_icons: ^1.0.2
  datetime_picker_formfield: null
  file_picker: null
  firebase_auth: null
  firebase_core: null
  firebase_storage: null
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_spinkit: ^5.1.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-0
  provider: ^5.0.0
  shared_preferences: ^2.0.6

dev_dependencies:
  change_app_package_name: null

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AlmaraiBold
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf

    - family: AlmaraiExtraBold
      fonts:
        - asset: assets/fonts/Almarai-ExtraBold.ttf

    - family: AlmaraiLight
      fonts:
        - asset: assets/fonts/Almarai-Light.ttf

    - family: AlmaraiRegular
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
